
/*********************************************************************************************

    This is public domain software that was developed by or for the U.S. Naval Oceanographic
    Office and/or the U.S. Army Corps of Engineers.

    This is a work of the U.S. Government. In accordance with 17 USC 105, copyright protection
    is not available for any work of the U.S. Government.

    Neither the United States Government, nor any employees of the United States Government,
    nor the author, makes any warranty, express or implied, without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or assumes any liability or
    responsibility for the accuracy, completeness, or usefulness of any information,
    apparatus, product, or process disclosed, or represents that its use would not infringe
    privately-owned rights. Reference herein to any specific commercial products, process,
    or service by trade name, trademark, manufacturer, or otherwise, does not necessarily
    constitute or imply its endorsement, recommendation, or favoring by the United States
    Government. The views and opinions of authors expressed herein do not necessarily state
    or reflect those of the United States Government, and shall not be used for advertising
    or product endorsement purposes.

*********************************************************************************************/

/********************************************************************
 *
 * Module Name : main.c
 *
 * Author/Date : Jan C. Depner
 *
 ********************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <getopt.h>
#include <math.h>
#include <sys/stat.h>
#include <sys/types.h>


/* Local Includes. */

#include "nvutility.h"

#include "version.h"


void usage ()
{
    fprintf (stderr, 
        "\nUsage: line_area [-w WIDTH -h HEIGHT] LINE_FILE\n");
    fprintf (stderr, "\nWhere:\n\n");
    fprintf (stderr, "\tLINE_FILE = .pts file name generated by pfm_view\n");
    fprintf (stderr, "\tWIDTH = width of output area files in meters (default=5000)\n");
    fprintf (stderr, "\tHEIGHT = height of output area files in meters (default=5000)\n\n");
    fflush (stderr);
}


int32_t main (int32_t argc, char **argv)
{
    char               file[512], string[256], cut[40], dir[512];
    int32_t            i, j, count = 0, total, icount, start, acount = 0;
    FILE               *fp, *out_fp;
    float              width, height, width_2;
    double             *x = NULL, *y = NULL, *ix = NULL, *iy = NULL, a0 = 6378137.0, 
                       b0 = 6356752.314245, dist, az, x_interval,
                       y_interval, start_az, lat[4], lon[4];
    char               c;
    extern char        *optarg;
    extern int         optind;


    printf ("\n\n %s \n\n\n", VERSION);



    width = 5000.0;
    height = 5000.0;


    while ((c = getopt (argc, argv, "w:h:")) != EOF)
      {
	switch (c)
          {
          case 'w':
            sscanf (optarg, "%f", &width);
            break;

          case 'h':
            sscanf (optarg, "%f", &height);
            break;

          default:
            usage ();
            exit (-1);
            break;
          }
      }

    width_2 = width / 2.0;
    height = height / 2.0;


    /* Make sure we got the mandatory file name argument.  */

    if (optind >= argc)
      {
        usage ();
        exit (-1);
      }


    strcpy (file, argv[optind]);

    if ((fp = fopen (file, "r")) == NULL)
      {
        perror (file);
        exit (-1);
      }


    while (fgets (string, sizeof (string), fp) != NULL)
      {
        x = (double *) realloc (x, sizeof (double) * (count + 1));
        if (x == NULL)
          {
            perror ("Allocating X memory");
            exit (-1);
          }

        y = (double *) realloc (y, sizeof (double) * (count + 1));
        if (y == NULL)
          {
            perror ("Allocating Y memory");
            exit (-1);
          }

        strcpy (cut, strtok (string, ","));
        posfix (cut, &y[count], POS_LAT);
        strcpy (cut, strtok (NULL, ","));
        posfix (cut, &x[count], POS_LON);

        count++;
      }

    fclose (fp);


    total = 0;
    for (i = 0 ; i < count - 1 ; i++)
      {
        invgp (a0, b0, y[i], x[i], y[i + 1], x[i + 1], &dist, &az);

        icount = dist / 100.0;
        x_interval = (x[i + 1] - x[i]) / (double) icount; 
        y_interval = (y[i + 1] - y[i]) / (double) icount; 

        ix = (double *) realloc (ix, sizeof (double) * (total + icount + 1));
        if (ix == NULL)
          {
            perror ("Allocating IX memory");
            exit (-1);
          }

        iy = (double *) realloc (iy, sizeof (double) * (total + icount + 1));
        if (iy == NULL)
          {
            perror ("Allocating IY memory");
            exit (-1);
          }

        for (j = 0 ; j <= icount ; j++)
          {
            ix[j + total] = x[i] + (double) j * x_interval;
            iy[j + total] = y[i] + (double) j * y_interval;
          }

        total += icount;
      }

    free (x);
    free (y);


    sprintf (dir, "%s_area_files", file);
#ifdef NVWIN3X
  #ifdef __MINGW64__
    if (_mkdir (dir))
  #else
    if (_mkdir (dir))
  #endif
#else
    if (mkdir (dir, 00777))
#endif
      {
        if (errno != 17)
          {
            perror (dir);
            exit (-1);
          }
      }


    start = 0;
    invgp (a0, b0, iy[0], ix[0], iy[1], ix[1], &dist, &start_az);

    for (i = 1 ; i < total ; i++)
      {
        invgp (a0, b0, iy[start], ix[start], iy[i], ix[i], &dist, &az);


        if (dist > height || i == total - 1)
          {
            az = fmod (start_az + 90.0, 360.0);

            newgp (iy[start], ix[start], az, width_2, &lat[0], &lon[0]);

            az = fmod (az + 180.0, 360.0);

            newgp (iy[start], ix[start], az, width_2, &lat[1], &lon[1]);


            start = i;


            if (i == total - 1)
              {
                invgp (a0, b0, iy[start - 1], ix[start - 1], iy[start], ix[start], &dist, 
                       &start_az);
              }
            else
              { 
                invgp (a0, b0, iy[start], ix[start], iy[start + 1], ix[start + 1], &dist, 
                       &start_az);
              }

            az = fmod (start_az + 90.0, 360.0);

            newgp (iy[start], ix[start], az, width_2, &lat[3], &lon[3]);

            az = fmod (az + 180.0, 360.0);

            newgp (iy[start], ix[start], az, width_2, &lat[2], &lon[2]);

            sprintf (string, "%s%1c%03d.are", dir, (char) SEPARATOR, acount++);
            if ((out_fp = fopen (string, "w")) == NULL)
              {
                perror (string);
                exit (-1);
              }


            for (j = 0 ; j < 4 ; j++)
                fprintf (out_fp, "%.9f,%.9f\n", lat[j], lon[j]);

            fclose (out_fp);
          }
      }

    free (ix);
    free (iy);


    fprintf (stdout, "\nCreated %d area files in %s\n\n", acount, dir);

    return (0);
}
